/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipodato;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
public class LlamarCategoria extends javax.swing.JPanel implements java.beans.Customizer {
    public String user ="postgres";
    public String pass ="napaminis";
    public String Productos="Productos";
    public String bd = "Stock";
    public final String host = "jdbc:postgresql://localhost:5432/";
    public Connection conexion = null;
    private Object bean;

    /**
     * Creates new customizer LlamarCategoria
     */
    public LlamarCategoria() {
        initComponents();
        try{           
  
            Class.forName("org.postgresql.Driver");
  
            conexion = DriverManager.getConnection(host+bd,user,pass);            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Hubo un problema con la conexion.\n"+e , "Verifiquelo",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    public void callcategoria(){
        DefaultTableModel cate=(DefaultTableModel)jTablacate.getModel();
        int rows = cate.getRowCount();
        for (int i = rows - 1; i >=0; i--){
        cate.removeRow(i); 
        }
        String SQL = "SELECT * FROM categorias"; 
        try {
            Statement statement = conexion.createStatement();
            ResultSet rs= statement.executeQuery(SQL);
            while(rs.next()){
                String idcateg=String.valueOf(rs.getInt("idcategoria"));
                String categ=String.valueOf(rs.getString("categoria"));
                String tbData[]={idcateg,categ};
                cate.addRow(tbData);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablacate = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTablacate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdCategoria", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(jTablacate);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablacate;
    // End of variables declaration//GEN-END:variables
}

