/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipodato;

/**
 *
 * @author ferch
 */
public class VentanaPrincipal extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jTextField1);
        jTextField1.setBounds(20, 130, 100, 20);

        jTextField2.setText("jTextField2");
        jDesktopPane1.add(jTextField2);
        jTextField2.setBounds(130, 130, 80, 20);

        jLabel1.setText("Producto");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(40, 100, 60, 20);

        jLabel2.setText("Categoría");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(140, 100, 60, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(480, 160, 340, 350);

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jDesktopPane1.add(jSpinner1);
        jSpinner1.setBounds(350, 50, 100, 20);

        jLabel3.setText("Stock Hospital Nacional de Itaugua");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(120, 30, 190, 14);

        jTextField3.setText("jTextField3");
        jDesktopPane1.add(jTextField3);
        jTextField3.setBounds(230, 130, 100, 20);

        jLabel4.setText("Cantidad");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(260, 100, 70, 14);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jDesktopPane1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 190, 430, 230);

        jLabel5.setText("Detalles");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(30, 170, 60, 14);

        jTextField4.setText("jTextField4");
        jDesktopPane1.add(jTextField4);
        jTextField4.setBounds(30, 460, 250, 40);

        jButton1.setText("jButton1");
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(700, 130, 73, 23);

        jTextField5.setText("jTextField5");
        jDesktopPane1.add(jTextField5);
        jTextField5.setBounds(560, 130, 120, 20);

        add(jDesktopPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}

